-- lsp.on_attach(function(client, bufnr)
-- 	local opts = { buffer = bufnr, remap = false }
--
-- 	if client.name == "angularls" then
-- 		for _, active_client in ipairs(vim.lsp.get_active_clients({ bufnr })) do
-- 			if active_client.name == "tsserver" then
-- 				active_client.stop()
-- 				break
-- 			end
-- 		end
-- 	end
--
--
-- lsp.configure("emmet_language_server", {
-- 	filetypes = {
-- 		"css",
-- 		"eruby",
-- 		"html",
-- 		"javascript",
-- 		"javascriptreact",
-- 		"less",
-- 		"sass",
-- 		"scss",
-- 		"svelte",
-- 		"pug",
-- 		"typescriptreact",
-- 		"vue",
-- 	},
-- 	init_options = {
-- 		--- @type table<string, any> https://docs.emmet.io/customization/preferences/
-- 		preferences = {},
-- 		--- @type "always" | "never" defaults to `"always"`
-- 		showexpandedabbreviation = "always",
-- 		--- @type boolean defaults to `true`
-- 		showabbreviationsuggestions = true,
-- 		--- @type boolean defaults to `false`
-- 		showsuggestionsassnippets = false,
-- 		--- @type table<string, any> https://docs.emmet.io/customization/syntax-profiles/
-- 		syntaxprofiles = {},
-- 		--- @type table<string, string> https://docs.emmet.io/customization/snippets/#variables
-- 		variables = {},
-- 		--- @type string[]
-- 		excludelanguages = {},
-- 	},
-- })
--
-- lsp.setup()
--
-- local diag_config = {
-- 	virtual_text = true,
-- 	underline = true,
-- 	update_in_insert = true,
-- }
--
-- vim.diagnostic.config(diag_config)
